### ISSUE TITLE
Desktop UI for v 1.0.0

### ISSUE THREAD

**Issue by Partical777** [Bal-Laedi/newsIntegration#9]
Refer : 
https://canals-amsterdam.nl/
- [x] Navbar UI
- [x] 背景 Mask Alpha值調整至0.65
- [x] 滑鼠 Scroll 橫向滑動
- [x] 移除 Hover 底線
- [x] Cursor 設定：Sidebar
- [x] Sidebar trigger icon
- [x] 中文字體：https://fonts.google.com/specimen/Noto+Sans+TC?subset=chinese-traditional
- [x] Nav Bar 顏色先用Sidebar UI 圖的酒紅色
- [x] 移除文章又見選取反白效果
- [x] Navbar icon 可點擊部分範圍過大
- [x] 隱藏 scroll bar
- [x] 所有新聞來源移除後的 bug
- [x] Hover 效果 background colour
- [x] Desktop UI change : Sidebar 右上角 X 更改，放大
- [x] 調整 nav bar index-z，永遠在最上方 (Sidebar 也不會蓋過他)
- [x] Sidebar 內，新聞來源 hover 範圍調整 (只有文字與上方直線可點擊)

**Comment by Partical777** [comment]
I'll provide these
- animation design (When toggle filter)
- nav bar 點開頁面設計
- 圖片載入 Mask (顯示 0~100% 頁面)

**Comment by shung-yang** [comment]
Due day 2020/6/24 23:00

**Comment by Partical777** [comment]
3. 圖片載入 Mask (顯示 0~100% 頁面)
<img width="818" alt="Screen Shot 2020-06-23 at 3 30 37 PM" src="https://user-images.githubusercontent.com/23421379/85373965-9e93cf00-b566-11ea-8f25-6140076ebb35.png">

With this loader effect:
https://codepen.io/corentinfardeau/pen/zBWLxV
https://codepen.io/GeoffreyCrofte/details/RWxoZR

**Comment by Partical777** [comment]
2. nav bar 點開頁面設計
<img width="1236" alt="Screen Shot 2020-06-23 at 4 51 17 PM" src="https://user-images.githubusercontent.com/23421379/85382709-d0f6f980-b571-11ea-9743-8649c89bcfeb.png">

**Comment by shung-yang** [comment]
Delay Due Day: 2020/6/25 23:00
尚差 navbar, 無限右滑可能問題

**Comment by shung-yang** [comment]
Delay Due Day: 2020/6/27 23:00
已找到scroll position 方法

**Comment by shung-yang** [comment]
Delay Due Day: 2020/6/29 4:00
尚差 navbar

**Comment by Partical777** [comment]
<img width="573" alt="Screen Shot 2020-07-24 at 2 12 44 PM" src="https://user-images.githubusercontent.com/23421379/88371274-48fd4d00-cdc6-11ea-9d31-581dfea1b77c.png">

新增 UI Task List - 移除文章上點選右鍵功能（以及右鍵時會選取文章反白效果）

**Comment by Partical777** [comment]
<img width="1337" alt="Screen Shot 2020-07-24 at 2 12 50 PM" src="https://user-images.githubusercontent.com/23421379/88371296-54e90f00-cdc6-11ea-9f41-5f21da0956a3.png">

注意上方紅匡處，他會持續轉圈，載入狀態不會停止，以及沒有 Title

**Comment by Partical777** [comment]
![Screen Shot 2020-07-24 at 3 45 27 PM](https://user-images.githubusercontent.com/23421379/88371333-66321b80-cdc6-11ea-9529-3676fcda4ff6.png)

點擊部分應該只會是比 Icon 稍微大一些，而不是整個藍色區域都可以點


---
Btw 你的 .Navbar 都用 inline-grid 了，.nav-item 就不要用 padding 去置中啊
直接在 .Navbar 加上
justify-content：center 就置中了
你用 padding 還會引起元素不可見的部分超出區域

**修正步驟：**
移除 .nav-item 之 padding
加上 .Navbar 之 justify-content：center

**Comment by Partical777** [comment]
隱藏 scroll bar 

教學：https://ithelp.ithome.com.tw/articles/10197593

**Comment by Partical777** [comment]
Sidebar 出現動畫 bug 解決方式

![Screen Shot 2020-07-24 at 4 35 06 PM](https://user-images.githubusercontent.com/23421379/88374072-ac3dae00-cdcb-11ea-9090-d45b37ae3892.png)

在調整 sidebar width 的 class 中
同時加上
left: -100vw
transition : left .65s ease-in-out

 (因為你的 width 設定為 100vw，所以相應的他要原始位置需要往左 100vw，原本動畫會卡就是因為他還是預設值 -350px，所以縮回去 350px 竟會瞬間消失。)
 (transition 時間加長，ease 改為 ease-in-out，因為我們的 width 比原本的加寬，時間延長看起來比較自然)

**Comment by Partical777** [comment]
Hover 圖片 background colour changing

:hover {
    background-color: rgba(80,0,36,0.65);
    transition: background-color 0.35s ease-in-out;    
}

**Comment by Partical777** [comment]
Hover 圖片視差效果
格子中圖片 hover 針對滑鼠位置相對移動

https://codepen.io/hexagoncircle/pen/jgGxKR
